# Generated by Django 5.1.6 on 2025-02-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_album_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField(max_length=100)),
                ('release_country', models.CharField(max_length=100)),
                ('mood', models.CharField(max_length=100)),
                ('lyrics', models.TextField(max_length=100)),
            ],
        ),
    ]
