# Generated by Django 5.1.6 on 2025-02-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_song_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(max_length=100),
        ),
    ]
